ui:
#  enabled: false
  image:
    pullPolicy: Always
  ingress:
    enabled: true
    hosts:
      - host: null
        paths:
          - /

api:
#  enabled: false
  image:
    pullPolicy: Always
  ingress:
    enabled: true
    hosts:
      - host: null
        paths:
          - /api/

iceciOperator:
#  enabled: false
  image:
    pullPolicy: Always
  persistence:
    sharedVolume:
      hostPath: /home/kkrampa/shared-storage
    dynamicVolume:
      hostPath: /home/kkrampa/dynamic-storage

sync:
#  enabled: false
  image:
    pullPolicy: Always
