{{- if and .Values.enableUI .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iceci.fullname" . }}-api
  labels:
    {{- include "iceci.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "iceci.api.selectorLabels" . | nindent 4 }}
{{- end -}}
