{{- if .Values.ui.ingress.enabled -}}
{{- $uiSvcPort := .Values.ui.service.port -}}
{{- $apiSvcPort := .Values.api.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "iceci.fullname" . }}
  labels:
    {{- include "iceci.labels" . | nindent 4 }}
  {{- with .Values.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ui.ingress.tls }}
  tls:
  {{- range .Values.ui.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- range .Values.api.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - http:
        paths:
        {{- range .Values.ui.ingress.hosts }}
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ include "iceci.fullname" $ }}-ui
              servicePort: {{ $uiSvcPort }}
          {{- end }}
        {{- end }}
        {{- range .Values.api.ingress.hosts }}
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ include "iceci.fullname" $ }}-api
              servicePort: {{ $apiSvcPort }}
          {{- end }}
        {{- end }}
{{- end }}
