{{- if .Values.ingress.enabled -}}
{{- $uiSvcPort := .Values.ui.service.port -}}
{{- $apiSvcPort := .Values.api.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "iceci.fullname" . }}
  labels:
    {{- include "iceci.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
      hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
  {{- end }}
{{- end }}
  rules:
{{- if .Values.ingress.hosts }}
{{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      - path: "/"
        backend:
          serviceName: {{ include "iceci.fullname" $ }}-ui
          servicePort: {{ $uiSvcPort }}
      - path: "/api/"
        backend:
          serviceName: {{ include "iceci.fullname" $ }}-api
          servicePort: {{ $apiSvcPort }}
        {{- end }}
{{- else }}
  - http:
      paths:
      - path: "/"
        backend:
          serviceName: {{ include "iceci.fullname" $ }}-ui
          servicePort: {{ $uiSvcPort }}
      - path: "/api/"
        backend:
          serviceName: {{ include "iceci.fullname" $ }}-api
          servicePort: {{ $apiSvcPort }}
{{- end }}
{{- end }}
