apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iceci.fullname" . }}-operator
  labels:
    {{- include "iceci.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.iceciOperator.replicaCount }}
  selector:
    matchLabels:
      {{- include "iceci.operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "iceci.operator.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "iceci.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.iceciOperator.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.iceciOperator.image.pullPolicy }}
          env:
          - name: ICECI_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "iceci-operator"
          - name: ICECI_DYNAMIC_PVC
            value: {{ include "iceci.fullname" . }}-dynamic
          - name: ICECI_SHARED_PVC
            value: {{ include "iceci.fullname" . }}-shared
          - name: ICECI_IMAGE_KANIKO
            value: "gcr.io/kaniko-project/executor:v0.16.0"
          - name: ICECI_IMAGE_UTILS
            value: "iceci/utils:latest"
          - name: ICECI_IMAGE_BUILDKIT
            value: "moby/buildkit:v0.6.4-rootless"
          - name: ICECI_STEP_SERVICE_ACCOUNT
            value: ice-operator-step
          - name: ICECI_DEFAULT_IMAGE_BUILDER
            value: buildkit
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
