{{- if .Values.iceciOperator.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "iceci.fullname" . }}
  labels:
    {{- include "iceci.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - "pods/log"
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - iceci-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - iceci.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - icekube.io
  resources:
  - '*'
  verbs:
  - '*'
{{- end -}}