{{- if .Values.iceciOperator.enabled -}}
{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "iceci.fullname" . }}
  labels:
    {{- include "iceci.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "iceci.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "iceci.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- end -}}
