apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "iceci.fullname" . }}-step
  labels:
    {{- include "iceci.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - patch
  - get
  - create
  - delete
