{{- if .Values.iceciOperator.enabled -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "iceci.fullname" . }}-step
  labels:
    {{- include "iceci.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "iceci.stepServiceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "iceci.fullname" . }}-step
  apiGroup: rbac.authorization.k8s.io
{{- end -}}