{{- if and .Values.storage.dynamicVolume.hostPath (not .Values.storage.dynamicVolume.existingClaim) -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    {{- include "iceci.labels" . | nindent 4 }}
    name: {{ template "iceci.fullname" . }}-dynamic
  name: {{ template "iceci.fullname" . }}-dynamic
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.storage.dynamicVolume.size }}
  hostPath:
    path: {{ required "dynamic.hostPath" .Values.storage.dynamicVolume.hostPath | quote }}
    type: DirectoryOrCreate
{{- end -}}