{{- if and .Values.storage.sharedVolume.hostPath (not .Values.storage.sharedVolume.existingClaim) -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    {{- include "iceci.labels" . | nindent 4 }}
    name: {{ template "iceci.fullname" . }}-shared
  name: {{ template "iceci.fullname" . }}-shared
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.storage.sharedVolume.size }}
  hostPath:
    path: {{ required "shared.hostPath" .Values.storage.sharedVolume.hostPath | quote }}
    type: DirectoryOrCreate
{{- end -}}