{{- if and .Values.ui.enabled  .Values.enableUI }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iceci.fullname" . }}-ui
  labels:
    {{- include "iceci.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "iceci.ui.selectorLabels" . | nindent 4 }}
{{- end -}}
